### ISSUE TITLE
Tensorboard log output AR50_90 value is for maxDets=1 per image

### ISSUE THREAD

**Issue by mkrupczak3** [roboflow/rf-detr#152]
### Search before asking

- [x] I have searched the RF-DETR issues and found no similar bug report.

### Bug

For finetuning training runs, I'm having a difficult time with the Tensorboard output from this repo and using it to track progress and performance.

My main issue stems from the graphs shown in Tensorboard for AP and AR. I really want to see a proper Recall statistic in the Tensorboard output as this is something I am trying to improve in my model with finetuning. Unfortunately, it seems the AR50_90 metric in Tensorboard is only for maxDets=1 per image. My training images (and also the COCO dataset and similar I believe) usually have more than 1 object in each image, so this metric is mostly irrelevant for finetuning runs.

As you can see from the screenshots below, the AR50_90 score shown in Tensorboard is only 0.375, while in the log output it shows as 0.970 when maxDets=100:

<img width="693" alt="Image" src="https://github.com/user-attachments/assets/8d20e9cb-aea5-422c-89af-c6da55c7450e" />

<img width="823" alt="Image" src="https://github.com/user-attachments/assets/7348645b-27b2-4f18-9f0e-a0f937297788" />

More broadly, I'd like to also be able to see charts in Tensorboard for metrics such as `loss_ce_unscaled`, `class_error_unscaled`, `loss_bbox_unscaled`, and `loss_ce_unscaled`, as well as their test and ema variants as mentioned by @isaacrob-roboflow in #93. Trying to interpret the trend of these metrics from just text log output is very difficult presently.

### Environment

N/A

### Minimal Reproducible Example

1. Start a finetuning run
2. Launch tensorboard on the run's output directory
3. Metrics are insufficient for evaluating performance and progress of training runs

### Are you willing to submit a PR?

- [x] Yes, I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @mkrupczak3 👋🏻 thanks for reporting this. It's obviously a bug. We should report value at maxDets=100. Could you submit a bug fix for this?

**Comment by mkrupczak3** [comment]
I'm out of office next week, I'm certainly willing to make and submit a PR for a fix after though

**Comment by mkrupczak3** [comment]
It looks like the matplotlib graphs also use the wrong metric for Recall, with maxDets=1:

![Image](https://github.com/user-attachments/assets/35e3bb4b-cf82-4089-a8d7-86a15d7e0c9c)

**Comment by SkalskiP** [comment]
I'll probably fix it on Monday.

**Comment by SkalskiP** [comment]
@mkrupczak3 I've just merged https://github.com/roboflow/rf-detr/pull/156. We're releasing RF-DETR v1.2.0 next week. If you'd like to use the fixed code before the release, please make sure to install it from source: `pip install git+https://github.com/roboflow/rf-detr.git`.

**Comment by SkalskiP** [comment]
I'm closing the issue for now. Feel free to reopen if you'll have more questions.

**Comment by mkrupczak3** [comment]
@SkalskiP @isaacrob-roboflow requesting this issue be re-opened. I installed the code from the latest commit in the develop branch (in which this PR is merged). I could be wrong, however it does not appear that PR #156 fully fixed the bug which causes the wrong recall score to appear. 

I also took a look in `util/metrics.py` and could not find the immediate cause of the wrong metric appearing:

<img width="809" alt="Image" src="https://github.com/user-attachments/assets/be548cf9-6699-4960-967c-1ae33b31da84" />

<img width="792" alt="Image" src="https://github.com/user-attachments/assets/9c0db079-0edd-4d2a-a953-9dad3d146760" />

<img width="937" alt="Image" src="https://github.com/user-attachments/assets/c91d7f70-6b63-42ef-8195-19fc0cd2b058" />

<img width="997" alt="Image" src="https://github.com/user-attachments/assets/bc8845d7-3f39-4bd5-bbdf-b19594ecb9e1" />

**Comment by mkrupczak3** [comment]
@SkalskiP @isaacrob-roboflow Any chance you could take another look and re-open this issue before v1.2.0 release? Pull requesst #171 on the develop branch does not seem to have fixed this issue

**Comment by mkrupczak3** [comment]
@SkalskiP @isaacrob-roboflow I have confirmed again in testing today that PR #156 did not fix issue #152 in the develop branch.

I did some more digging in the codebase but could not find the root cause. I'm pretty sure though that whatever is providing the `ema_test_coco_eval_bbox` array to metrics.py is providing the wrong metric

![Image](https://github.com/user-attachments/assets/c659c5a2-e485-4b48-9bdb-0508110dc1fe)

![Image](https://github.com/user-attachments/assets/90a50594-7a64-4faa-ab8f-e1af227c42aa)

![Image](https://github.com/user-attachments/assets/b5d2d67a-8a7a-498a-966e-57a72ae4ffc5)

**Comment by SkalskiP** [comment]
Hi @mkrupczak3 I just checked. I installed `pip install git+https://github.com/roboflow/rf-detr.git` and everything works as expected. 

<img width="652" alt="Image" src="https://github.com/user-attachments/assets/fd8cb196-987c-454a-a220-b29cb5bb13c5" />
<img width="652" alt="Image" src="https://github.com/user-attachments/assets/d14a0f44-ef3a-4539-8262-e5a5b2b539e2" />
<img width="652" alt="Image" src="https://github.com/user-attachments/assets/6801f1c7-cb4f-4338-8ee3-de350d0131f1" />
<img width="651" alt="Image" src="https://github.com/user-attachments/assets/78ae4b7d-05f2-4d46-ac48-308ffd015105" />
<img width="651" alt="Image" src="https://github.com/user-attachments/assets/24c5d5af-290b-4bf6-83b4-60eabd0f9a74" />
<img width="653" alt="Image" src="https://github.com/user-attachments/assets/0072f4af-e816-4db9-9dbc-3926eec3afe8" />
<img width="686" alt="Image" src="https://github.com/user-attachments/assets/2637b998-ecf4-4b3f-a544-6b40a7487aa9" />

**Comment by mkrupczak3** [comment]
@SkalskiP @isaacrob-roboflow Something weird must be going on then. I just tested a fresh pip install from the latest commit on main but got different results than you did. The issue is still present for me and I don't think it's anything to do with my local env. I made sure to purge everything from pip before as well:

![Image](https://github.com/user-attachments/assets/19b85e6d-aba9-42e6-b4a9-05b15e765e67)

![Image](https://github.com/user-attachments/assets/c6719b5e-9b64-42c0-a20a-45c863e36b94)

![Image](https://github.com/user-attachments/assets/99d52e04-65ab-4b26-9410-569006ab8bc5)

![Image](https://github.com/user-attachments/assets/22b8aee9-89fc-4a86-a262-3cc217508b23)

**Comment by mkrupczak3** [comment]
Just reinstalled everything from source with `pip -e` as a sanity check. Same result, the wrong metric is still used

**Comment by mkrupczak3** [comment]
Nevermind, it turns out that my Python environment was using an older, stale compiled cached version of rfdetr. If anybody else encounters this issue, make sure to remove all `.pyc` files in `rfdetr/__pycache__`. Also make sure that you clone from the develop branch with the following command:

```bash
pip install --upgrade --no-binary :all: git+https://github.com/roboflow/rf-detr.git@develop
```

Or alternatively, install directly from your cloned download:
```
pip install --upgrade -e .
```

This issue may safely remain closed

**Comment by RhysDeLoach** [comment]
I am experiencing this same issue when using WandB to show the AR50-90 metrics. Would it be possible to get this fixed as well?

Also, not bug related, but is this metric truly AR50_90 or AR50_95? Both AR and AP show as 50_95 in the coco eval but 50_90 in WandB.
